name: Print status
run-name: Get system information
on: push

jobs:
  get_status:
    name: Get system status...
    permissions: write-all
    runs-on: macos-latest
    defaults:
      run:
        working-directory: .
    env:
      name: Mladen
      age: 16
    steps:
      - name: Print test message using echo
        run: echo Hello World from MacOS ${{runner.name}} ${{runner.os}}
      - name: Test env vars
        run: |
            echo name = ${{env.name}} age = ${{env.age}}
            echo global var = ${{vars.GLOBAL_VAR}}
      - name : Check out current repo
        uses: actions/checkout@v4.2.2
      - name: Scan the content of the current repo and print out python script
        run: |
          ls -l
          cat main.py
        
      
