name: Print status
run-name: Get system information
on: push

jobs:
  get_status:
    name: Get system status...
    permissions: write-all
    runs-on: macos-latest
    outputs:
      "directory content": steps."Scan the content of the current repo and print out python script".outputs.content
    defaults:
      run:
        working-directory: .
    env:
      name: Mladen
      age: 16
    steps:
      - name: Print test message using echo
        run: echo Hello World from MacOS ${{runner.name}} ${{runner.os}}
      - name: Test env vars
        run: |
            echo name = ${{env.name}} age = ${{env.age}}
            echo global var = ${{vars.GLOBAL_VAR}}
      - name : Check out current repo
        uses: actions/checkout@v4.2.2
      - name: Scan the content of the current repo and print out python script
        run: |
          ls -l
          echo "content=$(ls -l)" >> "$GITHUB_OUTPUT"
          cat main.py
  read_output:
    name: Read output
    runs-on: 	ubuntu-latest
    needs: "get_status"
    steps:
      - name: Print working directory output from previous job
        run: echo ${{needs.get_status.outputs."directory content"}}
      
